language: python

services:
  - docker

python:
  - "3.6"

install:
  - make deps

script:
  - make lint
  - make test_xunit
  - make docker_build

after_success:
  - make docker_push

deploy:
  provider: heroku
  app: immense-fjord-21653
  api_key: ${HEROKU_API_KEY}